[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "nemesis"
version = "0.1.0"
description = "Reproducible management of numerical experiments"
readme = "README.md"
requires-python = ">=3.11"

dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
]

[project.scripts]
nemesis = "nemesis.main:main"

[tool.basedpyright]
reportAny = "none"

[tool.pyink]
line-length = 80
